class AppIcons {
  const AppIcons._();
  static const String cart = 'assets/icons/cart.svg';
  static const String favourite = 'assets/icons/fav.svg';
  static const String fav = 'assets/icons/fav.svg';
  static const String forbidden = 'assets/icons/forbidden.svg';
  static const String heart = 'assets/icons/heart.svg';
  static const String home = 'assets/icons/home.svg';
  static const String infoCircle = 'assets/icons/info_circle.svg';
  static const String information = 'assets/icons/information.svg';
  static const String lock = 'assets/icons/lock.svg';
  static const String logout = 'assets/icons/logout.svg';
  static const String messageQuestion = 'assets/icons/message_question.svg';
  static const String more = 'assets/icons/more.svg';
  static const String notification = 'assets/icons/notification.svg';
  static const String sms = 'assets/icons/sms.svg';
  static const String star = 'assets/icons/star.svg';
  static const String translate = 'assets/icons/translate.svg';
  static const String shieldTick = 'assets/icons/shield_tick.svg';
  static const String arrowUp = 'assets/icons/arrow _up.svg';
  static const String arrowDown = 'assets/icons/arrow _down.svg';
  static const String delete = 'assets/icons/delete.svg';
  static const String shoppingBag = 'assets/icons/shopping_bag.svg';
  static const String shop = 'assets/icons/shop.svg';
  static const String gallerySend = 'assets/icons/gallery_send.svg';
  static const String gift = 'assets/icons/gift.svg';
  static const String reminder = 'assets/icons/reminder.svg';
  static const String order = 'assets/icons/order.svg';
  static const String system = 'assets/icons/system.svg';
  static const String send = 'assets/icons/send_icon.svg';
  static const String link = 'assets/icons/link.svg';
  static const String audio = 'assets/icons/audio.svg';
  static const String camera = 'assets/icons/camera.svg';
  static const String document = 'assets/icons/document.svg';
  static const String gallery = 'assets/icons/gallery.svg';
  static const String location = 'assets/icons/location.svg';
  static const String polling = 'assets/icons/polling.svg';
}
