// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWYeR4jOjvetegFU8i333y2m5RcfTwPFk',
    appId: '1:165517394994:web:b94ac311f7ad62ad31682b',
    messagingSenderId: '165517394994',
    projectId: 'mega-intern-app',
    authDomain: 'mega-intern-app.firebaseapp.com',
    storageBucket: 'mega-intern-app.firebasestorage.app',
    measurementId: 'G-0RQY4ZXJ2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4Eo5kIqJJa9vNoKRA2YpMiR-XwF0gWbM',
    appId: '1:165517394994:android:fd944dd995b85a3b31682b',
    messagingSenderId: '165517394994',
    projectId: 'mega-intern-app',
    storageBucket: 'mega-intern-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcK0Tn5c4bH4HK5tYOdt41ACKNx2oksb0',
    appId: '1:165517394994:ios:b8824f9462b28a9831682b',
    messagingSenderId: '165517394994',
    projectId: 'mega-intern-app',
    storageBucket: 'mega-intern-app.firebasestorage.app',
    iosBundleId: 'com.example.megaEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcK0Tn5c4bH4HK5tYOdt41ACKNx2oksb0',
    appId: '1:165517394994:ios:b8824f9462b28a9831682b',
    messagingSenderId: '165517394994',
    projectId: 'mega-intern-app',
    storageBucket: 'mega-intern-app.firebasestorage.app',
    iosBundleId: 'com.example.megaEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWYeR4jOjvetegFU8i333y2m5RcfTwPFk',
    appId: '1:165517394994:web:0c7c8b6d9ae70c0431682b',
    messagingSenderId: '165517394994',
    projectId: 'mega-intern-app',
    authDomain: 'mega-intern-app.firebaseapp.com',
    storageBucket: 'mega-intern-app.firebasestorage.app',
    measurementId: 'G-9945FY40VK',
  );

}